author: Multitallented
database: false
author: Multitallented
authors: [chivers1234, Sevaron, Kiak, Phoenix_Frenzy]
description: Allows you to create structures and towns.
main: multitallented.redcastlemedia.bukkit.townships.Townships
name: Townships
startup: postworld
version: 3.0.1-b060
depend: [Vault]
commands:
   hs:
      aliases: ['township', 'townships', 'towns', 'town', 'to', 'hs']
      description: Townships commands
      usage: /<command>
permissions:
   townships.join:
       description: Allows players to join towns
       default: true
   townships.unlock:
       description: Allows players to unlock new regions
       default: op
   townships.create.all:
      description: Allows you to create a region of any type if you have the necessary materials
      default: op
   townships.admin:
      description: Lets you use admin commands
      default: op
   townships.group.default:
      description: Gives you the default group for region limitations
      default: true
loadafter: [Vault]